
# welcome to cirrus' dots :3


exec-once = waybar
exec-once = awww-daemon
exec-once = swaync
exec-once = fcitx5

$mod = SUPER

monitor = eDP-1, 1920x1200@59.99900, 0x0, 1


bind = $mod, RETURN, exec, kitty
bind = $mod_SHIFT, S, exec, hyprlock
bind = $mod, K, killactive
bind = $mod, SPACE, exec, rofi -show drun
bind = $mod, J, exec, rofi -show calc
bind = $mod_SHIFT, P, exec, grim -g "$(slurp -w 0)" - | wl-copy
bind = $mod, LEFT, movewindow, l
bind = $mod, DOWN, movewindow, d
bind = $mod, UP, movewindow, u
bind = $mod, RIGHT, movewindow, r
bind = $mod, F, fullscreen, 1
bind = $mod_SHIFT, M, togglefloating


bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

bind = $mod_SHIFT, 1, movetoworkspace, 1
bind = $mod_SHIFT, 2, movetoworkspace, 2
bind = $mod_SHIFT, 3, movetoworkspace, 3
bind = $mod_SHIFT, 4, movetoworkspace, 4
bind = $mod_SHIFT, 5, movetoworkspace, 5
bind = $mod_SHIFT, 6, movetoworkspace, 6
bind = $mod_SHIFT, 7, movetoworkspace, 7
bind = $mod_SHIFT, 8, movetoworkspace, 8
bind = $mod_SHIFT, 9, movetoworkspace, 9
bind = $mod_SHIFT, 0, movetoworkspace, 10

bindm = $mod, mouse:273, resizewindow
bindm = $mod, mouse:272, movewindow

bind = $mod_SHIFT, L, exec, zsh -i -c "/home/llylithe/.config/hypr/hyprsh/swww-sequential_wallpapers.sh"
bind = $mod_SIFT, L, exec, 
bind = $mod_SHIFT, R, exec, hyprctl reload
bind = $mod_SHIFT, E, exec, hyprctl dispatch exit

windowrule = opacity 0.9 0.7, match:class firefox
windowrule = opacity 0.85 0.8, match:class google-chrome
windowrule = opacity 0.8 0.7, match:class zen
windowrule = opacity 0.75 0.6, match:class kitty
windowrule = opacity 0.8 0.7, match:class discord
windowrule = opacity 0.8 0.7, match:class spotify
windowrule = opacity 0.8 0.8, match:class org.kde.dolphin
windowrule = opacity 0.8 0.7, match:class org.vinegarhq.Sober
windowrule = opacity 0.1, match:class rofi
windowrule = opacity 0.8 0.5, match:class obsidian
windowrule = opacity 0.75 0.5,match:class jetbrains-idea
windowrule = opacity 0.7 0.6, match:class Slack
windowrule = opacity 0.5 0.4, match:class org.pwmt.zathura
windowrule = opacity 0.8 0.7, match:class code-oss

layerrule = blur on, match:namespace rofi
layerrule = xray on, match:namespace rofi
layerrule = blur on, match:namespace waybar

general {
  gaps_in = 5
  gaps_out = 10
  border_size = 0
  gaps_workspaces = 5
}


decoration {
  rounding = 10

  blur {
    enabled = true
    ignore_opacity = true
    passes = 4
    size = 7
    xray = true
    popups = true
  }

  shadow {
    enabled = true
    range = 10
    render_power = 1
    color = 0xee12161c
  }
}

animations {
    enabled = true, animations
        bezier = winIn, 0.1, 1.0, 0.1, 1.0
        bezier = winOut, 0.1, 1.0, 0.1, 1.0
        bezier = smoothOut, 0.5, 0, 0.99, 0.99
        bezier = layerOut,0.23,1,0.32,1
        animation = windowsIn, 1, 7, winIn, slide
        animation = windowsOut, 1, 3, smoothOut, slide
        animation = windowsMove, 3, 7, winIn, slide
        animation = workspacesIn, 1, 8, winIn, slide
        animation = workspacesOut, 1, 8, winOut, slide
        animation = layersIn, 1, 10, winIn, slide
        animation = layersOut, 1, 3, layerOut, popin 50%
}

input {
  mouse_refocus = true
}

misc {
  disable_hyprland_logo = true
}

